[package]
name = "elsdc"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
opencv = { version = "0.92.0", features = ["clang-runtime"] }

[build-dependencies]
cc = "1.1.5"
bindgen = "0.69.4"
